/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherGradesRouteImport } from './routes/teacher.grades'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherCoursesRouteImport } from './routes/teacher.courses'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as StudentScheduleRouteImport } from './routes/student.schedule'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentGradesRouteImport } from './routes/student.grades'
import { Route as StudentEnrollmentRouteImport } from './routes/student.enrollment'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentAccountStatusRouteImport } from './routes/student.account-status'
import { Route as StudentAcademicHistoryRouteImport } from './routes/student.academic-history'
import { Route as FinanceTuitionPaymentsRouteImport } from './routes/finance.tuition-payments'
import { Route as FinancePaymentHistoryRouteImport } from './routes/finance.payment-history'
import { Route as FinanceDashboardRouteImport } from './routes/finance.dashboard'
import { Route as FinanceCoursePaymentsRouteImport } from './routes/finance.course-payments'
import { Route as ExecutiveDashboardRouteImport } from './routes/executive.dashboard'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminPeriodsRouteImport } from './routes/admin.periods'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherGradesRoute = TeacherGradesRouteImport.update({
  id: '/teacher/grades',
  path: '/teacher/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherCoursesRoute = TeacherCoursesRouteImport.update({
  id: '/teacher/courses',
  path: '/teacher/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/teacher/attendance',
  path: '/teacher/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/student/schedule',
  path: '/student/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/student/grades',
  path: '/student/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEnrollmentRoute = StudentEnrollmentRouteImport.update({
  id: '/student/enrollment',
  path: '/student/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAccountStatusRoute = StudentAccountStatusRouteImport.update({
  id: '/student/account-status',
  path: '/student/account-status',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAcademicHistoryRoute = StudentAcademicHistoryRouteImport.update({
  id: '/student/academic-history',
  path: '/student/academic-history',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTuitionPaymentsRoute = FinanceTuitionPaymentsRouteImport.update({
  id: '/finance/tuition-payments',
  path: '/finance/tuition-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePaymentHistoryRoute = FinancePaymentHistoryRouteImport.update({
  id: '/finance/payment-history',
  path: '/finance/payment-history',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceDashboardRoute = FinanceDashboardRouteImport.update({
  id: '/finance/dashboard',
  path: '/finance/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCoursePaymentsRoute = FinanceCoursePaymentsRouteImport.update({
  id: '/finance/course-payments',
  path: '/finance/course-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveDashboardRoute = ExecutiveDashboardRouteImport.update({
  id: '/executive/dashboard',
  path: '/executive/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPeriodsRoute = AdminPeriodsRouteImport.update({
  id: '/admin/periods',
  path: '/admin/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/executive/dashboard': typeof ExecutiveDashboardRoute
  '/finance/course-payments': typeof FinanceCoursePaymentsRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/payment-history': typeof FinancePaymentHistoryRoute
  '/finance/tuition-payments': typeof FinanceTuitionPaymentsRoute
  '/student/academic-history': typeof StudentAcademicHistoryRoute
  '/student/account-status': typeof StudentAccountStatusRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/enrollment': typeof StudentEnrollmentRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/grades': typeof TeacherGradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/executive/dashboard': typeof ExecutiveDashboardRoute
  '/finance/course-payments': typeof FinanceCoursePaymentsRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/payment-history': typeof FinancePaymentHistoryRoute
  '/finance/tuition-payments': typeof FinanceTuitionPaymentsRoute
  '/student/academic-history': typeof StudentAcademicHistoryRoute
  '/student/account-status': typeof StudentAccountStatusRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/enrollment': typeof StudentEnrollmentRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/grades': typeof TeacherGradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/executive/dashboard': typeof ExecutiveDashboardRoute
  '/finance/course-payments': typeof FinanceCoursePaymentsRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/payment-history': typeof FinancePaymentHistoryRoute
  '/finance/tuition-payments': typeof FinanceTuitionPaymentsRoute
  '/student/academic-history': typeof StudentAcademicHistoryRoute
  '/student/account-status': typeof StudentAccountStatusRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/enrollment': typeof StudentEnrollmentRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/grades': typeof TeacherGradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/periods'
    | '/admin/students'
    | '/admin/teachers'
    | '/executive/dashboard'
    | '/finance/course-payments'
    | '/finance/dashboard'
    | '/finance/payment-history'
    | '/finance/tuition-payments'
    | '/student/academic-history'
    | '/student/account-status'
    | '/student/dashboard'
    | '/student/enrollment'
    | '/student/grades'
    | '/student/profile'
    | '/student/schedule'
    | '/teacher/attendance'
    | '/teacher/courses'
    | '/teacher/dashboard'
    | '/teacher/grades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/periods'
    | '/admin/students'
    | '/admin/teachers'
    | '/executive/dashboard'
    | '/finance/course-payments'
    | '/finance/dashboard'
    | '/finance/payment-history'
    | '/finance/tuition-payments'
    | '/student/academic-history'
    | '/student/account-status'
    | '/student/dashboard'
    | '/student/enrollment'
    | '/student/grades'
    | '/student/profile'
    | '/student/schedule'
    | '/teacher/attendance'
    | '/teacher/courses'
    | '/teacher/dashboard'
    | '/teacher/grades'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/periods'
    | '/admin/students'
    | '/admin/teachers'
    | '/executive/dashboard'
    | '/finance/course-payments'
    | '/finance/dashboard'
    | '/finance/payment-history'
    | '/finance/tuition-payments'
    | '/student/academic-history'
    | '/student/account-status'
    | '/student/dashboard'
    | '/student/enrollment'
    | '/student/grades'
    | '/student/profile'
    | '/student/schedule'
    | '/teacher/attendance'
    | '/teacher/courses'
    | '/teacher/dashboard'
    | '/teacher/grades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPeriodsRoute: typeof AdminPeriodsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  ExecutiveDashboardRoute: typeof ExecutiveDashboardRoute
  FinanceCoursePaymentsRoute: typeof FinanceCoursePaymentsRoute
  FinanceDashboardRoute: typeof FinanceDashboardRoute
  FinancePaymentHistoryRoute: typeof FinancePaymentHistoryRoute
  FinanceTuitionPaymentsRoute: typeof FinanceTuitionPaymentsRoute
  StudentAcademicHistoryRoute: typeof StudentAcademicHistoryRoute
  StudentAccountStatusRoute: typeof StudentAccountStatusRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentEnrollmentRoute: typeof StudentEnrollmentRoute
  StudentGradesRoute: typeof StudentGradesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherCoursesRoute: typeof TeacherCoursesRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherGradesRoute: typeof TeacherGradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/grades': {
      id: '/teacher/grades'
      path: '/teacher/grades'
      fullPath: '/teacher/grades'
      preLoaderRoute: typeof TeacherGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/courses': {
      id: '/teacher/courses'
      path: '/teacher/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/teacher/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/schedule': {
      id: '/student/schedule'
      path: '/student/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/student/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/enrollment': {
      id: '/student/enrollment'
      path: '/student/enrollment'
      fullPath: '/student/enrollment'
      preLoaderRoute: typeof StudentEnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/account-status': {
      id: '/student/account-status'
      path: '/student/account-status'
      fullPath: '/student/account-status'
      preLoaderRoute: typeof StudentAccountStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/academic-history': {
      id: '/student/academic-history'
      path: '/student/academic-history'
      fullPath: '/student/academic-history'
      preLoaderRoute: typeof StudentAcademicHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/tuition-payments': {
      id: '/finance/tuition-payments'
      path: '/finance/tuition-payments'
      fullPath: '/finance/tuition-payments'
      preLoaderRoute: typeof FinanceTuitionPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payment-history': {
      id: '/finance/payment-history'
      path: '/finance/payment-history'
      fullPath: '/finance/payment-history'
      preLoaderRoute: typeof FinancePaymentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/dashboard': {
      id: '/finance/dashboard'
      path: '/finance/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof FinanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/course-payments': {
      id: '/finance/course-payments'
      path: '/finance/course-payments'
      fullPath: '/finance/course-payments'
      preLoaderRoute: typeof FinanceCoursePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive/dashboard': {
      id: '/executive/dashboard'
      path: '/executive/dashboard'
      fullPath: '/executive/dashboard'
      preLoaderRoute: typeof ExecutiveDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/periods': {
      id: '/admin/periods'
      path: '/admin/periods'
      fullPath: '/admin/periods'
      preLoaderRoute: typeof AdminPeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPeriodsRoute: AdminPeriodsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  ExecutiveDashboardRoute: ExecutiveDashboardRoute,
  FinanceCoursePaymentsRoute: FinanceCoursePaymentsRoute,
  FinanceDashboardRoute: FinanceDashboardRoute,
  FinancePaymentHistoryRoute: FinancePaymentHistoryRoute,
  FinanceTuitionPaymentsRoute: FinanceTuitionPaymentsRoute,
  StudentAcademicHistoryRoute: StudentAcademicHistoryRoute,
  StudentAccountStatusRoute: StudentAccountStatusRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentEnrollmentRoute: StudentEnrollmentRoute,
  StudentGradesRoute: StudentGradesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherCoursesRoute: TeacherCoursesRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherGradesRoute: TeacherGradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
